coverage:
  status:
    project:
      default:
        # https://docs.codecov.com/docs/commit-status#informational
        informational: true
        target: 80%
    patch:
      default:
        informational: true
        target: 80%
github_checks:
    annotations: false
