[package]
authors = ["Dilshod Tadjibaev (@antimora)"]
edition.workspace = true
license.workspace = true
name = "mnist-inference-web"
publish = false
version.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
default = ["ndarray"]

ndarray = ["burn/ndarray"]
wgpu = ["burn/wgpu"]

[dependencies]
burn = { path = "../../crates/burn", default-features = false }
serde = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = { workspace = true }
console_error_panic_hook = { workspace = true }

[dev-dependencies]
pollster = { workspace = true }
